### PR TITLE
Fix report

### LINKED ISSUE #97: Adapt fronted for new data model

### LINKED ISSUE #98: Adjust testing for new data model

### LINKED ISSUE #99: Finalize code for freeze

### PR DESCRIPTION
**Pull request by BlakeDonn**
### What does this PR do?

* Adapts frontend to match BE data-model changes
* Finalizes styling for report 
* Fixes small bugs in testing
* Cleans up unnecessary code

### Where should the reviewer start?

* Start by checking out the deployed branch! [link](https://dream-home-cap.herokuapp.com/)

### How should this be manually tested?

* Work through different user stories, check output is correct

### Any background context you want to provide?

* Going to clean up the rest of the logs and other errors

### What are the relevant tickets?

closes #97 
closes #98 
closes #99

### CODE REVIEW

File: src/apiCalls.tsx [hunk 1]
```diff
@@ -3,7 +3,8 @@ import { Answers } from './types';
 export const getQuestions = async () => {
   const response = await fetch('https://dreamhome-mvp.herokuapp.com/api/v1/education')
   if (response.ok) {
-    return await response.json()
+    let final =  await response.json()
+    return final.data
```
Comment (Atos20) [inline src/apiCalls.tsx:7]: I liked the name of the `let` variable.

**Review by Atos20 — APPROVED** [review]

**Review by timkeresey — APPROVED** [review]
I think, if the opportunity presents itself, this is a good candidate for refactoring. Maybe fetch the report into a local state for a container, then pass each object down to individually created components that represent each data point we are presenting to the user.
